springdoc:
  swagger-ui:
    path: "swagger-ui"

management:
  server:
    port: 8080

server:
  port: 8083

app:
  bot:
    name: "tinkoff-bot"
    token: 6100537283:AAEW5JLiyRQ3_2CXp12Yzv4LcIujjLWC-ys
  scrapper:
    url: "http://localhost:8080"
  rabbit-queue:
    exchange-name: updates
    queue-name: updates.queue
    routing-key: upd

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${QUEUE_USERNAME}
    password: ${QUEUE_PASSWORD}
